name: Build Docs
on: [push]
jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build
              uses: jnanadarshan/mkdocs-build-action@v1

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: site